language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

install:
  - pip install 'flake8' 'coverage<4' coveralls

script:
  - coverage run setup.py test
  - flake8 requirements

after_success: coveralls
